### ISSUE TITLE
Version tag?

### ISSUE THREAD

**Issue by Thunder7ga** [timstephens24/channelsdvr-docker#3]
Does this support version tags?   Channels DVR has lots of "pre-release" updates that from time to time would be of value... not sure if this works with changing the tag from "latest" to something else is baked in to get those pre-releases when desired.

**Comment by timstephens24** [comment]
It does not, the only tag I use is latest and beta. Both of these are just for the container itself and not the Channels-DVR install. I rarely update the beta unless I'm making big sweeping changes, but the latest is updated once a week. The hard thing with Channels is that the app data lives in the same base folder as the folder for the versions, for example the data folder has all of the epg, logs, certs, and other stuff. If you compare that to something like plex, the app executables live completely separate from the data folder, so it's easier to do that.

I'm not sure if it's really worth it, though, since the channels-dvr folder is going to have six older versions in there. I currently see six versions in my folder going back to the May 11th, and I update to the latest pre-release every day at 0500. You can roll back to an older version that's in that folder at any time. The "latest" linked file is a link to the most recent version, and if you want to point to an older version you just need to change the folder that is linked.. If you want to rollback to an older version you'd need to change the folder link that latest is linked to. To do that for example to go back to version "2023.05.11.1938":

`cd /opt/channels-dvr && ln -nsf 2023.05.11.1938 latest`

You could potentially do something on your own to backup those folders to another location and then if you need to revert copy an old version folder over, stop the docker, run a similar command to the above, and then start the docker back up.

Interested in your thoughts, though!

**Comment by Thunder7ga** [comment]
Ah, that makes sense to me.  I wouldn't change your process.   Thanks for the added info.

**Comment by timstephens24** [comment]
I'm going to package setup.sh in the /usr/local/bin folder in the container. This allows you to roll back to whatever version you want by running this command (example version is 2023.05.20.0631 with the container name of channels-dvr):

`docker exec -it channels-dvr bash -c "DVR_VERSION=2023.05.20.0631 /usr/local/bin/setup.sh" && docker restart channels-dvr`

This works really well to downgrade to previous pre-release versions really easy. I did test rolling back stable releases, which you can do, but Channels will download the most recent stable release when it starts, and then will potentially automatically update itself. This is normal Channels behavior.

**Comment by timstephens24** [comment]
This is now in the most recent update and the README is updated.

If you just want to download a specific version w/o updating Channels just run:

`docker exec -it channels-dvr bash -c "DVR_VERSION=2023.05.20.0631 DOWNLOAD_ONLY=1 /usr/local/bin/setup.sh"`
